name: 'dbt_alert'
config-version: 2
require-dbt-version: [">=1.6.0", "<2.0.0"]

profile: 'dbt_alert'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  # dbt_alert__mailing_list: "mail1@domain.com, mail2@domain.com" # mandatory
  # dbt_alert__dbt_cloud_access_url: "cloud.getdbt.com" # check https://docs.getdbt.com/docs/cloud/manage-access/sso-overview#auth0-multi-tenant-uris
  # dbt_alert_notification_integration_id: my_notification_integration_name # default value = "ni_dbt_alert_" ~ project_name ~ "_" ~ target.name
  # dbt_alert_notification_integration_usage_role: my_notification_integration_usage_role # default value = target.role
  # dbt_alert__jobs: <list of job names split by comma> # job name doesn't need to include prefix of "dbt_alert_job__"
