name: 'dbt_alert_test'
version: '0.0.0'
config-version: 2

profile: 'dbt_alert'

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  dbt_alert__mailing_list: dat-nguyen-channel-aaaaibyq5hfrhsjq7le3brmydm@infinitelambda.slack.com
  dbt_alert__jobs: "sample_2,sample_3"

on-run-start:
  - >
    {{ log("💡 Integration object [" ~ dbt_alert.create_or_get_resource(create=true) ~ "] will need manually creating to avoid failing tests", true) if execute }}
    {{ log("💡 See above generated script", true) if execute }}

on-run-end:
  - "{{ dbt_alert.execute_job(job_name='sample_1') }}"
#   - "{{ dbt_alert.execute_jobs() }}" # rely on `dbt_alert__jobs` variable
